# Generated by Django 6.0.3 on 2026-03-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_rename_notes_pharmacyorder_order_instructions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacyorder",
            name="order_number",
            field=models.CharField(max_length=30),
        ),
    ]
