# Generated by Django 6.0.3 on 2026-03-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_alter_pharmacyorder_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacyorder",
            name="order_number",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="pharmacyproduct",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
