# Generated by Django 4.2.28 on 2026-03-04 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyuser_city_companyuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_medical_conditions', models.TextField(blank=True, default='', help_text='e.g. Diabetes, Hypertension, Asthma')),
                ('allergies_dietary_or_prescription', models.TextField(blank=True, default='', help_text='e.g. Penicillin, Peanuts, Gluten')),
                ('current_medication_history', models.TextField(blank=True, default='', help_text='e.g. Metformin 500mg daily')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_information',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('number_of_next_of_kin', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_contacts',
            },
        ),
    ]
