# Generated by Django 4.2.28 on 2026-04-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_companyuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
