# Generated by Django 6.0.3 on 2026-03-27 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homecare", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homecarerequest",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="homecarerequest",
            name="location_text",
        ),
        migrations.RemoveField(
            model_name="homecarerequest",
            name="longitude",
        ),
        migrations.AlterField(
            model_name="homecareservice",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
