# Generated by Django 6.0.3 on 2026-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homecare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecarerequest",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
