# Generated by Django 4.2.28 on 2026-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationnote',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
