# Generated by Django 4.2.28 on 2026-04-07 00:20

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0003_alter_doctoravailability_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='board_certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_school',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_memberships',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='consultation/doctors/avatars'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='residency',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='DoctorOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='incomplete', max_length=20)),
                ('step_personal_done', models.BooleanField(default=False)),
                ('step_professional_done', models.BooleanField(default=False)),
                ('step_medical_done', models.BooleanField(default=False)),
                ('step_availability_done', models.BooleanField(default=False)),
                ('step_documents_done', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='consultation.doctorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_onboarding',
            },
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_license', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='consultation/doctors/documents/licenses')),
                ('medical_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('medical_license_expiry', models.DateField(blank=True, null=True)),
                ('medical_certificate', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='consultation/doctors/documents/certificates')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='consultation.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_documents',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='consultation.doctorprofile')),
            ],
            options={
                'db_table': 'consultation_doctor_availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
